[functions]
  external_node_modules = ["express", "cheerio"]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**"]

[functions.server]
  timeout = 26
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"
